# Generated by Django 4.2.10 on 2026-10-08 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("practices", "0003_alter_domain_status_and_more"),
        ("appointments", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="ai_summary",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="intent",
            field=models.CharField(blank=True, default="appointment", max_length=50),
        ),
        migrations.AddField(
            model_name="appointment",
            name="internal_notes",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="appointment",
            name="message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="practice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="practices.practice",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="preferred_date",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="appointment",
            name="preferred_time",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="appointment",
            name="priority",
            field=models.CharField(
                choices=[
                    ("LOW", "Low"),
                    ("NORMAL", "Normal"),
                    ("HIGH", "High"),
                    ("URGENT", "Urgent"),
                ],
                default="NORMAL",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="response_draft",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="response_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="service_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="appointment",
            name="source_website",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="appointment",
            name="urgency",
            field=models.CharField(
                choices=[
                    ("LOW", "Low"),
                    ("NORMAL", "Normal"),
                    ("HIGH", "High"),
                    ("URGENT", "Urgent"),
                ],
                default="NORMAL",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="practice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="practices.practice",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="confirmation_code",
            field=models.CharField(
                blank=True, db_index=True, max_length=32, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="patient_email",
            field=models.EmailField(blank=True, db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to="appointments.service",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Review"),
                    ("contacted", "Contacted"),
                    ("confirmed", "Confirmed"),
                    ("cancelled", "Cancelled"),
                    ("completed", "Completed"),
                    ("no_show", "No Show"),
                    ("spam", "Spam"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["practice", "status"], name="appointment_practic_e7931a_idx"
            ),
        ),
    ]
