# Generated by Django 5.0.6 on 2026-10-08 12:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PracticeSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("practice_name", models.CharField(max_length=200)),
                ("practice_email", models.EmailField(max_length=254)),
                ("practice_phone", models.CharField(blank=True, max_length=20)),
                ("practice_address", models.TextField(blank=True)),
                ("practice_website", models.URLField(blank=True)),
                (
                    "practice_timezone",
                    models.CharField(
                        default="America/New_York",
                        max_length=50,
                        verbose_name="Timezone",
                    ),
                ),
                ("widget_enabled", models.BooleanField(default=True)),
                ("widget_color", models.CharField(default="#2563EB", max_length=7)),
                ("widget_title", models.CharField(default="HeyJarvis", max_length=100)),
                (
                    "widget_greeting",
                    models.CharField(
                        default="Hello! How can I help you today?", max_length=200
                    ),
                ),
                ("ai_provider", models.CharField(default="openai", max_length=50)),
                ("ai_temperature", models.FloatField(default=0.7)),
                ("ai_max_tokens", models.IntegerField(default=500)),
                ("notification_email", models.EmailField(blank=True, max_length=254)),
                ("notification_webhook", models.URLField(blank=True)),
                ("notify_on_new_conversation", models.BooleanField(default=True)),
                ("notify_on_appointment", models.BooleanField(default=True)),
                ("notify_on_escalation", models.BooleanField(default=True)),
                ("auto_reply_enabled", models.BooleanField(default=True)),
                ("auto_reply_delay_minutes", models.IntegerField(default=15)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Practice Settings",
                "verbose_name_plural": "Practice Settings",
            },
        ),
        migrations.CreateModel(
            name="WidgetInstall",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "widget_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("site_url", models.URLField()),
                ("is_active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "installed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                (
                    "practice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="widgets",
                        to="dashboard.practicesettings",
                    ),
                ),
            ],
            options={
                "ordering": ["-installed_at"],
            },
        ),
    ]
