# Generated by Django 4.2.10 on 2026-10-08 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(blank=True, default="staff", max_length=20),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("AGENCY_ADMIN", "Agency Admin"),
                    ("PRACTICE_ADMIN", "Practice Admin"),
                    ("FRONT_DESK", "Front Desk"),
                    ("OWNER", "Owner"),
                    ("ADMIN", "Admin"),
                ],
                default="FRONT_DESK",
                max_length=20,
            ),
        ),
    ]
