# Generated by Antigravity for automated production seeding
from django.db import migrations


def seed_demo_accounts(apps, schema_editor):
    try:
        from apps.users.seed_data import seed_all_demo_data
        seed_all_demo_data()
    except Exception as e:
        print(f"Warning during seed migration: {e}")


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_user_type_alter_user_role"),
        ("practices", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_demo_accounts, reverse_code=migrations.RunPython.noop),
    ]
