# Generated by Django 5.0.6 on 2026-10-08 12:12

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIInteractionLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("provider", models.CharField(db_index=True, max_length=50)),
                ("model", models.CharField(db_index=True, max_length=100)),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("chat", "Chat"),
                            ("email_draft", "Email Draft"),
                            ("intent_classification", "Intent Classification"),
                            ("appointment_booking", "Appointment Booking"),
                            ("summary", "Summary"),
                        ],
                        max_length=30,
                    ),
                ),
                ("prompt_tokens", models.IntegerField(default=0)),
                ("completion_tokens", models.IntegerField(default=0)),
                ("total_tokens", models.IntegerField(default=0)),
                ("latency_ms", models.IntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
