# Generated by Django 5.0.6 on 2026-10-08 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ai_service", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="aiinteractionlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ai_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="aiinteractionlog",
            index=models.Index(
                fields=["provider", "created_at"], name="ai_service__provide_64bd74_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiinteractionlog",
            index=models.Index(
                fields=["interaction_type", "created_at"],
                name="ai_service__interac_402351_idx",
            ),
        ),
    ]
