# Generated by Django 4.2.10 on 2026-10-10 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("practices", "0005_booking_rules_handoff_ai"),
        ("ai_service", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiinteractionlog",
            name="practice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ai_logs",
                to="practices.practice",
            ),
        ),
        migrations.AlterField(
            model_name="aiinteractionlog",
            name="interaction_type",
            field=models.CharField(
                choices=[
                    ("chat", "Chat"),
                    ("email_draft", "Email Draft"),
                    ("intent_classification", "Intent Classification"),
                    ("appointment_booking", "Appointment Booking"),
                    ("summary", "Summary"),
                    ("escalation", "Escalation"),
                    ("error", "Error"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddIndex(
            model_name="aiinteractionlog",
            index=models.Index(
                fields=["practice", "created_at"], name="ai_service__practic_11a8f8_idx"
            ),
        ),
    ]
