# Generated by Django 4.2.10 on 2026-10-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practices", "0002_auditlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domain",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Verification"),
                    ("CONNECTED", "Connected"),
                    ("INVALID_DOMAIN", "Invalid Domain"),
                    ("DISABLED", "Disabled"),
                ],
                default="CONNECTED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="practicesettings",
            name="notification_emails",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Email addresses to notify per intent: {general: '...', emergency: '...'}",
            ),
        ),
    ]
