# Generated by Django 5.0.6 on 2026-10-08 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practices", "0003_alter_domain_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="practicesettings",
            name="notify_on_patient_reply",
            field=models.BooleanField(default=True),
        ),
    ]
