# Generated by Django 4.2.10 on 2026-10-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practices", "0004_practicesettings_notify_on_patient_reply"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingrules",
            name="cancellation_notice_hours",
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.AddField(
            model_name="bookingrules",
            name="custom_instructions",
            field=models.TextField(blank=True, max_length=4000),
        ),
        migrations.AddField(
            model_name="bookingrules",
            name="emergency_phone",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="bookingrules",
            name="handoff_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="bookingrules",
            name="handoff_message",
            field=models.TextField(blank=True),
        ),
    ]
