# Generated by Django 5.0.6 on 2026-10-08 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("emails", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="emailthread",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_email_threads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="email",
            name="thread",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emails",
                to="emails.emailthread",
            ),
        ),
        migrations.AddIndex(
            model_name="emailthread",
            index=models.Index(
                fields=["patient_email", "status"],
                name="emails_emai_patient_ae8e9b_idx",
            ),
        ),
    ]
