# Generated by Django 4.2.10 on 2026-10-10 05:54

from django.db import migrations, models
import django.db.models.deletion


def backfill_practice(apps, schema_editor):
    """Link existing threads to their practice using the id previously stored in metadata."""
    EmailThread = apps.get_model('emails', 'EmailThread')
    Practice = apps.get_model('practices', 'Practice')
    valid_ids = set(Practice.objects.values_list('id', flat=True))
    for thread in EmailThread.objects.filter(practice__isnull=True).iterator():
        raw = (thread.metadata or {}).get('practice_id')
        try:
            pid = int(raw)
        except (TypeError, ValueError):
            continue
        if pid in valid_ids:
            EmailThread.objects.filter(pk=thread.pk).update(practice_id=pid)


class Migration(migrations.Migration):

    dependencies = [
        ("practices", "0004_practicesettings_notify_on_patient_reply"),
        ("emails", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailcadence",
            name="practice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_cadences",
                to="practices.practice",
            ),
        ),
        migrations.AddField(
            model_name="emailthread",
            name="practice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_threads",
                to="practices.practice",
            ),
        ),
        migrations.RunPython(backfill_practice, migrations.RunPython.noop),
    ]
