# Generated by Django 5.2.18 on 2026-10-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0003_email_practice_scope"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="status",
            field=models.CharField(
                choices=[
                    ("sending", "Sending"),
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                    ("draft", "Draft"),
                    ("received", "Received"),
                ],
                default="draft",
                max_length=10,
            ),
        ),
    ]
