# Generated by Django 4.2.10 on 2026-10-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0003_add_practice_and_fields"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="conversation",
            new_name="conversatio_practic_aa155e_idx",
            old_name="conv_practice_status_idx",
        ),
        migrations.RenameIndex(
            model_name="conversation",
            new_name="conversatio_practic_6bd45c_idx",
            old_name="conv_practice_lead_idx",
        ),
        migrations.AlterField(
            model_name="conversation",
            name="patient_email",
            field=models.EmailField(blank=True, db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("completed", "Completed"),
                    ("abandoned", "Abandoned"),
                    ("handoff", "Handoff to Staff"),
                    ("closed", "Closed"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
